-- MySQL Script generated by MySQL Workbench
-- Tue Oct 25 04:23:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema study_connectWeb3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema study_connectWeb3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `study_connectWeb3` ;
USE `study_connectWeb3` ;

-- -----------------------------------------------------
-- Table `study_connectWeb3`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_connectWeb3`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `commentTitle` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `commentText` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `study_connectWeb3`.`boards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_connectWeb3`.`boards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `boardTitle` VARCHAR(64) CHARACTER SET 'utf8mb3' NOT NULL,
  `boardText` VARCHAR(64) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `commenter`
    FOREIGN KEY (`id`)
    REFERENCES `study_connectWeb3`.`comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `study_connectWeb3`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `study_connectWeb3`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `tell` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `userpw` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `username` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `nickname` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `gender` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `email` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `address` VARCHAR(64) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
